# Name of the GitHub Action workflow
name: Terraform Deploy

# Trigger workflow manually using the "Run workflow" button
on:
  workflow_dispatch:
    inputs:
      action:                     # Input variable
        description: "Choose Terraform Action"   # Description shown in UI
        required: true            # Must select before running workflow
        default: "apply"          # Default value
        type: choice              # Creates a dropdown menu
        options:
          - apply                 # Option 1
          - destroy               # Option 2

jobs:
  terraform:
    runs-on: ubuntu-latest        # GitHub Action runner OS

    env:
      # AWS credentials stored inside GitHub Secrets for security
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1  # Set AWS region

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Step 2: Install Terraform on the runner
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Step 3: Initialize Terraform (downloads plugins, setups backend)
      - name: Terraform Init
        run: terraform init

      # Step 4: Validate Terraform syntax
      - name: Terraform Validate
        run: terraform validate

      # Step 5: Create a plan file and save it as "tfplan"
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Step 6: Based on user input, apply OR destroy
      - name: Terraform Apply or Destroy
        run: |
          # If user selected "apply" in GitHub Actions UI
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            echo "Running terraform apply..."
            terraform apply -auto-approve tfplan

          # Else (means user selected "destroy")
          else
            echo "Running terraform destroy..."
            terraform destroy -auto-approve
          fi
          # "fi" means "end of if" in shell script
